project:
  type: website

website:
  title: "blog"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: http://www.linkedin.com/in/jiang-dayuan
    page-footer: "Copyright 2021, Norah Jones" 
  google-analytics: "UA-78379810-2"
format:
  html:
    theme: cosmo
    css: styles.css


