project:
  type: website

website:
  title: "blog"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: http://www.linkedin.com/in/jiang-dayuan
format:
  html:
    theme: cosmo
    css: styles.css



