project:
  type: website

website:
  title: "blog"
  google-analytics: "G-8BFRN648V7"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: http://www.linkedin.com/in/jiang-dayuan
  site-url: 'https://jiang.jp'
  site-path: '/'
  
format:
  html:
    theme: cosmo
    css: styles.css



